### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by dongkun01** [RayVentura/ShortGPT#24]
Hello, brother. Can it support short video generation in Chinese?

**Comment by KalvinThien** [comment]
![image](https://github.com/RayVentura/ShortGPT/assets/120565705/f64af8d7-6422-47f7-9f64-fda9eff808df)
ElevenLab do not support Chinese language

**Comment by RayVentura** [comment]
Yes, thanks @KalvinThien , we have to wait for ElevenLabs to support it, or if you have a suggestion of another TTS engine we can implement, I'm more than happy to try!

**Comment by KalvinThien** [comment]
I suggest using the edge-tts python module, because it actually reads pretty well, if there are more customizations like pitch, volume, and rate, the sound will be 100% unique.
you can try demo here , unlimited characters , with male and female voices : http://159.223.53.224:8501/Tao_Giong_Doc .
here is the voice list: https://github.com/rany2/edge-tts/blob/master/src/edge_tts/list_voices.py

Please translate into your language for ease of use.

**Comment by RayVentura** [comment]
I am definitely planning to add it, it seems like the best free easy alternative so far, thanks for the demo, it's pretty solid.
Created a task: https://github.com/RayVentura/ShortGPT/issues/25
You can track overall progress here: https://github.com/users/RayVentura/projects/1/
