### ISSUE TITLE
Adding edge_tts as a free voice alternative 

### ISSUE THREAD

**Issue by RayVentura** [RayVentura/ShortGPT#25]
Task description:
Adding edge_tts python module as a the `edgeVoiceModule` under the shortGPT/audio/
https://pypi.org/project/edge-tts/

**Comment by KalvinThien** [comment]
I'm not a programmer, but I have a lot of time, and also research some programs from youtube. so how can i help you to add edge-tts ?
do you need the processing code that i am doing here : http://159.223.53.224:8501/Tao_Giong_Doc_v2 ?
This is the program I sent you last time, but upgraded to be able to customize rate, pitch, volume, unlimited characters, and will have high uniqueness for voice, avoid being considered by youtube as voice spam.

**Comment by RayVentura** [comment]
> I'm not a programmer, but I have a lot of time, and also research some programs from youtube. so how can i help you to add edge-tts ? do you need the processing code that i am doing here : http://159.223.53.224:8501/Tao_Giong_Doc_v2 ? This is the program I sent you last time, but upgraded to be able to customize rate, pitch, volume, unlimited characters, and will have high uniqueness for voice, avoid being considered by youtube as voice spam.

You can do a pull request with the code in a VoiceModule?

**Comment by KalvinThien** [comment]
I don't quite understand it either, but can I add a few languages available to you, then you can call it later, okay?

Since Edge-TTS doesn't need an API and I don't know how to add Languages to other files, so I added it straight to 1 list and the function that generates voice like this, you see if it can help you reduce your time, I am glad to have contributed 1 little effort to your great program 

https://github.com/KalvinThien/ShortGPT/blob/stable/shortGPT/audio/edge_voice.py

**Comment by RayVentura** [comment]
> 

Thinks immensely, I've looked at your code, and I'm actually implementing Edge_tts in more than 80 languages, look at :
https://github.com/RayVentura/ShortGPT/commit/d5b0a4d6b961c1fd7c7aee785c2f1890e32a0aa2
The voice module works as standalone, I've tested it in Chinese, russian, ect...
I'm currently working on implementing the engine in all classes and the web User Interface. Thanks a lot @KalvinThien .

**Comment by KalvinThien** [comment]
That's great, that would be quite a step forward.
However, you should also note that edge-tts currently supports 1 male and female voice. No tone of voice either. That's why I often add pitch, rate, volumn parameters to change the voice, because Youtube, tiktok will often turn off monetization if using AI voice too much!

**Comment by RayVentura** [comment]
> use Youtube, tiktok will often turn off monetization if using AI voice too much!

Oh, that's interesting, I didn't know that. Later on, I'm going to make it randomly adjust those parameters.

**Comment by RayVentura** [comment]
Done.
