### ISSUE TITLE
features of the program or bugs ?

### ISSUE THREAD

**Issue by KalvinThien** [RayVentura/ShortGPT#9]
Hi RayVentura, I noticed in the Automate a video with stock assets feature 🎞️. When creating a video if I manually enter 1 separate content scrips will result in longer content. At this time, the program increases the running speed to give less than 1 minute. This made the video run extremely fast, I tried to slow down when the sound broke. 
can add an option so that if I tick it will not squeeze it down to less than 1 minute (this is very good if I make longer videos uploaded to some other platforms like Facebook, Pinterest).

this video is so fast : https://youtu.be/mruAxRsBKUI
thank you very much

**Comment by RayVentura** [comment]
You're definitely right, this was a feature to always speed up a video to get it to a Shorts format. But for the video with stock assets, I forget to remove it, since it's not particularly supposed to give out a Short. 

I just fixed the error, pull the latest version, or re-run your google colab, this shouldn't happen anymore.

**Comment by KalvinThien** [comment]
Do you have buymeacoffee?
I want to send you 1 cup of coffee
